### PR TITLE
RI-244: Update RPC-Designate for Queens

### PR DESCRIPTION
**Pull request by leader716**
There were a couple of changes that needed to be made to get RPC-Designate
to work with a Queens deployment. Updated the functions to recognize the
queens version and updated gating to test against a queens deployment

### CODE REVIEW

**Comment by leader716** [comment]
recheck_cit_xenial_pike_deploy

**Comment by leader716** [comment]
recheck_cit_xenial_pike_deploy

**Comment by Frank-ZhangXin** [comment]
recheck_cit_xenial_pike_deploy
Failed with unrelated error: python symlink ...

**Comment by Frank-ZhangXin** [comment]
fatal: [aio1_logstash_container-6b94d4fc]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service logstash: host"}

**Comment by mendeni** [comment]
recheck_cit_xenial_pike_deploy

**Pull request merged**
