### PR TITLE
RE-36 Saved image skips deployment of OpenStack

### PR DESCRIPTION
**Pull request by mattt416**
When gating using a saved rpc-openstack image, skip the deployment of
OpenStack infrastructure and services.

### CODE REVIEW

**Comment by mattt416** [comment]
Still testing this, please hold off on merging. :)

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
recheck_cit_xenial_functional_test

**Comment by mattt416** [comment]
Testing looks good, but my pike test failed with the following:

```
12:51:31 TASK [Get Modern PIP] **********************************************************
12:51:32 FAILED - RETRYING: Get Modern PIP (5 retries left).
12:51:36 FAILED - RETRYING: Get Modern PIP (4 retries left).
12:51:40 FAILED - RETRYING: Get Modern PIP (3 retries left).
12:51:43 FAILED - RETRYING: Get Modern PIP (2 retries left).
12:51:46 FAILED - RETRYING: Get Modern PIP (1 retries left).
12:51:48 fatal: [prdmxspd-2-e8e1]: FAILED! => {"attempts": 5, "changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for bootstrap.pypa.io:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: (\"bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'tlsv1 alert protocol version')],)\",)."}
```

Not sure if that was a transient failure?

**Comment by leader716** [comment]
Going to merge, I expect the pike test failure.

**Pull request merged**
