### PR TITLE
RI-661 Ajust pre script for propoer mnaio case

### PR DESCRIPTION
**Pull request by Frank-ZhangXin**
Previous commit which changed RE_JOB_IMAGE cases was not proper.
Add MNAIO image condition detecting in code, and his would help
applying designate onto host correctly.

### CODE REVIEW

**Comment by Frank-ZhangXin** [comment]
my own branch name is not accurate, please ignore that.

**Comment by leader716** [comment]
recheck_all

**Comment by Frank-ZhangXin** [comment]
recheck_xenial_snapshot_newton_deploy

**Comment by Frank-ZhangXin** [comment]
"nc: unix connect failed: Connection refused" on both rocky gating

**Pull request merged**
